/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicajflex;

import com.mycompany.practicajflex.jflex.CounterLexer;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author drymnz
 */
public class Start extends javax.swing.JFrame {

    private final String textOneVowel = "Cantidad de palabras que tengan una vocal :";
    private final String textTwoVowel = "Cantidad de palabras que tengan dos vocal :";
    private final String textThreeVowel = "Cantidad de palabras que tengan tres vocal :";
    private final String textFourVowel = "Cantidad de palabras que tengan cuatro vocal :";
    private final String textFiveVowel = "Cantidad de palabras que tengan cindo vocal :";
    private final String textInteger = "Cantidad de enteros :";
    private final String textErro = "Ingrese texto";

    private CounterLexer test;

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        loadText();
    }

    private void loadText() {
        numberWordsOneVowel.setText(textOneVowel);
        numberWordsTwoVowel.setText(textTwoVowel);
        numberWordsThreeVowel.setText(textThreeVowel);
        numberWordsFourVowel.setText(textFourVowel);
        numberWordsFiveVowel.setText(textFiveVowel);
        numberInteger.setText(textInteger);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaText = new javax.swing.JTextArea();
        button = new javax.swing.JButton();
        numberWordsOneVowel = new javax.swing.JLabel();
        numberWordsTwoVowel = new javax.swing.JLabel();
        numberWordsThreeVowel = new javax.swing.JLabel();
        numberWordsFourVowel = new javax.swing.JLabel();
        numberWordsFiveVowel = new javax.swing.JLabel();
        numberInteger = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listNumber = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaText.setColumns(20);
        areaText.setRows(5);
        jScrollPane1.setViewportView(areaText);

        button.setText("One Button");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        numberWordsOneVowel.setText("jLabel1");

        numberWordsTwoVowel.setText("jLabel1");

        numberWordsThreeVowel.setText("jLabel1");

        numberWordsFourVowel.setText("jLabel1");

        numberWordsFiveVowel.setText("jLabel1");

        numberInteger.setText("jLabel1");

        listNumber.setColumns(20);
        listNumber.setRows(5);
        listNumber.setEnabled(false);
        jScrollPane2.setViewportView(listNumber);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberWordsOneVowel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberWordsTwoVowel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberWordsThreeVowel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberWordsFourVowel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberWordsFiveVowel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberInteger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(button)
                .addGap(18, 18, 18)
                .addComponent(numberWordsOneVowel)
                .addGap(18, 18, 18)
                .addComponent(numberWordsTwoVowel)
                .addGap(18, 18, 18)
                .addComponent(numberWordsThreeVowel)
                .addGap(18, 18, 18)
                .addComponent(numberWordsFourVowel)
                .addGap(18, 18, 18)
                .addComponent(numberWordsFiveVowel)
                .addGap(18, 18, 18)
                .addComponent(numberInteger)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        if (!areaText.getText().isEmpty()) {
            Reader reader = new StringReader(areaText.getText());
            test = new CounterLexer(reader);
            int output;
            try {
                output = test.yylex();
                while (output != CounterLexer.YYEOF) {
                    test.yylex();
                }
                update();
            } catch (IOException ex) {
                Logger.getLogger(Start.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, textErro);
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void update() {
        numberWordsOneVowel.setText(textOneVowel + test.getCountOneVowel());
        numberWordsTwoVowel.setText(textTwoVowel + test.getCountTwoVowel());
        numberWordsThreeVowel.setText(textThreeVowel + test.getCountThreeVowel());
        numberWordsFourVowel.setText(textFourVowel + test.getCountFourVowel());
        numberWordsFiveVowel.setText(textFiveVowel + test.getCountFiveVowel());
        numberInteger.setText(textInteger + test.getCountNum());
        listNumber.setText(test.getListNumber());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Start window = new Start();
                window.setVisible(true);
                window.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaText;
    private javax.swing.JButton button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea listNumber;
    private javax.swing.JLabel numberInteger;
    private javax.swing.JLabel numberWordsFiveVowel;
    private javax.swing.JLabel numberWordsFourVowel;
    private javax.swing.JLabel numberWordsOneVowel;
    private javax.swing.JLabel numberWordsThreeVowel;
    private javax.swing.JLabel numberWordsTwoVowel;
    // End of variables declaration//GEN-END:variables
}
